// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxuP7aaWTyRDYtJj7tUjf66erBfytK4l8',
    appId: '1:159283539978:web:7edc8b53d282e269de2ff3',
    messagingSenderId: '159283539978',
    projectId: 'viber-8252c',
    authDomain: 'viber-8252c.firebaseapp.com',
    storageBucket: 'viber-8252c.appspot.com',
    measurementId: 'G-72GMR3VQW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVZ2woq5ozINSCaZAgLT3mrE-ooVP4KMU',
    appId: '1:159283539978:android:947b9dfd1bb60213de2ff3',
    messagingSenderId: '159283539978',
    projectId: 'viber-8252c',
    storageBucket: 'viber-8252c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP5362JEJQIXRtoa4QplCFMG2QreO4qPc',
    appId: '1:159283539978:ios:d3648b0a0e709a11de2ff3',
    messagingSenderId: '159283539978',
    projectId: 'viber-8252c',
    storageBucket: 'viber-8252c.appspot.com',
    iosBundleId: 'com.example.viber',
  );
}
